name: Tests (using Docker)

on: [workflow_call]

jobs:
  test:
    strategy:
      matrix:
        dockerfile-suffix: [
        "python35", "python36",
        ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./tests/dockerfiles/Dockerfile.${{ matrix.dockerfile-suffix }}
          push: false
          load: true
          tags: test:latest

      - name: Test
        run: |
          mkdir output
          docker run --rm --mount type=bind,src=./output,dst=/output test:latest

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage - docker - ${{ matrix.dockerfile-suffix }}.xml
          path: ./output/coverage.xml
